#! /bin/bash
source ~/python-2.6/virtenv/bin/activate

chmod +x $OPENSHIFT_REPO_DIR/.openshift/cron/hourly/StreamTwit.py
nohup python $OPENSHIFT_REPO_DIR/.openshift/cron/hourly/StreamTwit.py &> /dev/null &